# Generated by Django 5.0.6 on 2024-07-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('network_computer_virus', models.BooleanField(default=False)),
                ('network_firewall_misconfigurations', models.BooleanField(default=False)),
                ('network_insecure_remote_access', models.BooleanField(default=False)),
                ('open_ports', models.JSONField(default=list)),
                ('services', models.JSONField(default=dict)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('os_info', models.CharField(max_length=200)),
                ('os_command_injection_vulnerable', models.BooleanField(default=False)),
                ('os_remote_code_execution_vulnerable', models.BooleanField(default=False)),
                ('os_privilege_escalation_vulnerable', models.BooleanField(default=False)),
                ('os_misconfigurations', models.TextField(default='None')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('web', 'Web'), ('os', 'Operating System'), ('network', 'Network')], max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('host', models.CharField(max_length=200)),
                ('server', models.CharField(default='Unknown', max_length=200)),
                ('powered_by', models.CharField(default='Unknown', max_length=200)),
                ('sql_injection_vulnerable', models.BooleanField(default=False)),
                ('xss_vulnerable', models.BooleanField(default=False)),
                ('command_injection_vulnerable', models.BooleanField(default=False)),
                ('lfi_vulnerable', models.BooleanField(default=False)),
                ('rfi_vulnerable', models.BooleanField(default=False)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
