# Generated by Django 5.0.6 on 2024-07-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_networkinfo_networkscanresult_recommendation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkInfo',
        ),
        migrations.DeleteModel(
            name='NetworkScanResult',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='WebScanResult',
        ),
    ]
